### PR TITLE
Remove deprecated OpenSSL syntax

### PR DESCRIPTION
**Pull request by Xanders**

### CODE REVIEW

**Comment by michael-garland** [comment]
@sandric Are you still supporting this gem? Any chance we can get this PR merged so we can stop seeing a deprecation warning?

**Comment by sandric** [comment]
Sorry, no, was working on it long time ago. I'll merge pr and I should add notice to description that is not maintained.

**Review by sandric — APPROVED** [review]

**Comment by michael-garland** [comment]
Thanks @sandric! We have been using the gem for a while and it has worked great for us so we appreciate you creating it.

**Comment by michael-garland** [comment]
@sandric When do you think the new version will be up on RubyGems?

**Comment by sandric** [comment]
Pushed updated version to rubygems

**Comment by michael-garland** [comment]
@sandric Sorry to keep bothering you with this but as soon as I upgraded to 0.0.7, I started getting this error: `uninitialized constant DisqusRails` from my initializer. Reverting to 0.0.6 fixes the problem. Any thoughts on what might be wrong with 0.0.7?

**Pull request merged**
